package seers.irutils.entity;
// Generated Nov 18, 2015 8:59:09 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BugCommit generated by hbm2java
 */
@Entity
@Table(name="bug_commit"
    ,catalog="tomcat"
)
public class BugCommit  implements java.io.Serializable {


     private Integer id;
     private int bugId;
     private String summary;
     private String description;
     private Date reportTime;
     private String reporter;
     private String assignee;
     private String status;
     private String product;
     private String component;
     private String importance;
     private String commit;
     private String author;
     private Date commitTime;
     private String log;
     private String files;

    public BugCommit() {
    }

    public BugCommit(int bugId, String summary, String description, Date reportTime, String reporter, String assignee, String status, String product, String component, String importance, String commit, String author, Date commitTime, String log, String files) {
       this.bugId = bugId;
       this.summary = summary;
       this.description = description;
       this.reportTime = reportTime;
       this.reporter = reporter;
       this.assignee = assignee;
       this.status = status;
       this.product = product;
       this.component = component;
       this.importance = importance;
       this.commit = commit;
       this.author = author;
       this.commitTime = commitTime;
       this.log = log;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="bug_id", nullable=false)
    public int getBugId() {
        return this.bugId;
    }
    
    public void setBugId(int bugId) {
        this.bugId = bugId;
    }

    
    @Column(name="summary", nullable=false, length=65535)
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="report_time", nullable=false, length=19)
    public Date getReportTime() {
        return this.reportTime;
    }
    
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    
    @Column(name="reporter", nullable=false, length=50)
    public String getReporter() {
        return this.reporter;
    }
    
    public void setReporter(String reporter) {
        this.reporter = reporter;
    }

    
    @Column(name="assignee", nullable=false, length=50)
    public String getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="product", nullable=false, length=50)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }

    
    @Column(name="component", nullable=false, length=50)
    public String getComponent() {
        return this.component;
    }
    
    public void setComponent(String component) {
        this.component = component;
    }

    
    @Column(name="importance", nullable=false, length=50)
    public String getImportance() {
        return this.importance;
    }
    
    public void setImportance(String importance) {
        this.importance = importance;
    }

    
    @Column(name="commit", nullable=false, length=50)
    public String getCommit() {
        return this.commit;
    }
    
    public void setCommit(String commit) {
        this.commit = commit;
    }

    
    @Column(name="author", nullable=false, length=50)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="commit_time", nullable=false, length=19)
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    
    @Column(name="log", nullable=false, length=65535)
    public String getLog() {
        return this.log;
    }
    
    public void setLog(String log) {
        this.log = log;
    }

    
    @Column(name="files", nullable=false, length=16777215)
    public String getFiles() {
        return this.files;
    }
    
    public void setFiles(String files) {
        this.files = files;
    }




}


