package seers.irutils.entity;
// Generated Nov 18, 2015 8:59:09 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FileHistory generated by hbm2java
 */
@Entity
@Table(name="file_history"
    ,catalog="tomcat"
)
public class FileHistory  implements java.io.Serializable {


     private Integer id;
     private int docId;
     private String fileName;
     private String bugId;

    public FileHistory() {
    }

    public FileHistory(int docId, String fileName, String bugId) {
       this.docId = docId;
       this.fileName = fileName;
       this.bugId = bugId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="doc_id", nullable=false)
    public int getDocId() {
        return this.docId;
    }
    
    public void setDocId(int docId) {
        this.docId = docId;
    }

    
    @Column(name="file_name", nullable=false)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="bug_id", nullable=false, length=65535)
    public String getBugId() {
        return this.bugId;
    }
    
    public void setBugId(String bugId) {
        this.bugId = bugId;
    }




}


